### ISSUE TITLE
[Not An Issue] Edit the read me

### ISSUE THREAD

**Issue by Bandit-code** [Itz-Hyperz/HyperzFiveM-Base#1]
You do not need the patron key for phone it requires one sync but that can be enabled now due to the new update for fivem :)

**Comment by Itz-Hyperz** [comment]
This is designed for people who are just getting into FiveM development, and want to start off well. You do however need the key for Mumble-VOIP and Mumble-VOIP requires OneSync, you also need it for EUP, so I'm just leaving it there for now.

**Comment by Bandit-code** [comment]
Well i have muble on a test server and it works and also if you lower the player limt to under 8 their is a way to bypass the eup thing but for new people this sounds great

**Comment by Itz-Hyperz** [comment]
Yeah, except nobody would want an 8 player max server, so Imma just leave it.

**Comment by Itz-Hyperz** [comment]
I remember the hard times of learning FiveM development, how it worked and such, across multiple failed servers, and little knowledge. Hell at one point IceyyM8 called me an idiot and "not a real dev" back in like march of 2020 after joining a server of his. So I just wanted to make it easier, I have grown a lot in the FiveM community in general, and have learned a ton of development skills. So I'm just gonna keep this how it is at the moment. Thanks anyways.

**Comment by Bandit-code** [comment]
Okay I was just informing you for new players this is great
